// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA6Hi67ZNKuT4fvPcysIpgvkoa68K1wKV0',
    appId: '1:417706160769:web:5eda9f9b5926e33714d380',
    messagingSenderId: '417706160769',
    projectId: 'dalisocial-d92cc',
    authDomain: 'dalisocial-d92cc.firebaseapp.com',
    storageBucket: 'dalisocial-d92cc.firebasestorage.app',
    measurementId: 'G-EF9F1K2G1X',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAdV_PahvQLHRjPvmba1vXnfZ5h2roY1xM',
    appId: '1:417706160769:android:78373a867b48641614d380',
    messagingSenderId: '417706160769',
    projectId: 'dalisocial-d92cc',
    storageBucket: 'dalisocial-d92cc.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD7lZX9TfiYs_NRlcLLmnKUaFOdt2LayzY',
    appId: '1:417706160769:ios:40b7c9b93959bba614d380',
    messagingSenderId: '417706160769',
    projectId: 'dalisocial-d92cc',
    storageBucket: 'dalisocial-d92cc.firebasestorage.app',
    iosBundleId: 'com.example.untitled',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD7lZX9TfiYs_NRlcLLmnKUaFOdt2LayzY',
    appId: '1:417706160769:ios:40b7c9b93959bba614d380',
    messagingSenderId: '417706160769',
    projectId: 'dalisocial-d92cc',
    storageBucket: 'dalisocial-d92cc.firebasestorage.app',
    iosBundleId: 'com.example.untitled',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA6Hi67ZNKuT4fvPcysIpgvkoa68K1wKV0',
    appId: '1:417706160769:web:9ebad4f8f246da3414d380',
    messagingSenderId: '417706160769',
    projectId: 'dalisocial-d92cc',
    authDomain: 'dalisocial-d92cc.firebaseapp.com',
    storageBucket: 'dalisocial-d92cc.firebasestorage.app',
    measurementId: 'G-ER7D5TEYD0',
  );
}
